# Generated by Django 6.0.2 on 2026-04-15 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of favorite items.', verbose_name='Favorites Count'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255, verbose_name='Game Name')),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('NES', 'NES'), ('Famicom', 'Famicom'), ('SNES', 'SNES'), ('Super Famicom', 'Super Famicom'), ('Nintendo 64', 'Nintendo 64'), ('GameCube', 'GameCube'), ('Wii', 'Wii'), ('Wii U', 'Wii U'), ('Nintendo Switch', 'Nintendo Switch'), ('Game Boy', 'Game Boy'), ('Game Boy Color', 'Game Boy Color'), ('Game Boy Advance', 'Game Boy Advance'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Sega Master System', 'Sega Master System'), ('Sega Genesis / Mega Drive', 'Sega Genesis / Mega Drive'), ('Sega CD', 'Sega CD'), ('32X', '32X'), ('Sega Saturn', 'Sega Saturn'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Game Gear', 'Game Gear'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation Portable (PSP)', 'PlayStation Portable (PSP)'), ('PlayStation Vita', 'PlayStation Vita'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Atari', 'Atari'), ('Other', 'Other')], max_length=200, verbose_name='Platform')),
                ('screenshot', models.ImageField(help_text='Max size: 5MB. Allowed formats: .png .jpg .jpeg .webp', upload_to='screenshots/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Screenshot Image')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Favorited At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_screenshots', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('screenshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.screenshot', verbose_name='Screenshot')),
            ],
            options={
                'verbose_name': 'Favorite Screenshot',
                'verbose_name_plural': 'Favorite Screenshots',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'screenshot')},
            },
        ),
    ]
