# Generated by Django 6.0.2 on 2026-04-14 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('NES', 'NES'), ('Famicom', 'Famicom'), ('SNES', 'SNES'), ('Super Famicom', 'Super Famicom'), ('Nintendo 64', 'Nintendo 64'), ('GameCube', 'GameCube'), ('Wii', 'Wii'), ('Wii U', 'Wii U'), ('Nintendo Switch', 'Nintendo Switch'), ('Game Boy', 'Game Boy'), ('Game Boy Color', 'Game Boy Color'), ('Game Boy Advance', 'Game Boy Advance'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Sega Master System', 'Sega Master System'), ('Sega Genesis / Mega Drive', 'Sega Genesis / Mega Drive'), ('Sega CD', 'Sega CD'), ('32X', '32X'), ('Sega Saturn', 'Sega Saturn'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Game Gear', 'Game Gear'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation Portable (PSP)', 'PlayStation Portable (PSP)'), ('PlayStation Vita', 'PlayStation Vita'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Atari', 'Atari'), ('MAME', 'MAME'), ('FinalBurn NEO', 'FinalBurn NEO'), ('RetroArch', 'RetroArch')], max_length=255, verbose_name='Platform')),
                ('bios_file', models.FileField(help_text='Max size: 5GB. Allowed formats: .bin .rom .zip .tar.gz .pup', upload_to='bios/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin', 'rom', 'zip', 'gz', 'pup'])], verbose_name='BIOS File')),
                ('description', models.TextField(help_text='Description of the BIOS file(s)', verbose_name='Description')),
                ('source', models.CharField(choices=[('Dumped from original hardware', 'Dumped from original hardware'), ('Unknown source', 'Unknown source'), ('Other', 'Other')], max_length=255, verbose_name='Upload Source')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Downloads')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_bios', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'BIOS',
                'verbose_name_plural': 'BIOS Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
