# Generated by Django 6.0.2 on 2026-04-17 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('platform', models.CharField(choices=[('NES', 'NES'), ('Famicom', 'Famicom'), ('SNES', 'SNES'), ('Super Famicom', 'Super Famicom'), ('Nintendo 64', 'Nintendo 64'), ('GameCube', 'GameCube'), ('Wii', 'Wii'), ('Wii U', 'Wii U'), ('Nintendo Switch', 'Nintendo Switch'), ('Game Boy', 'Game Boy'), ('Game Boy Color', 'Game Boy Color'), ('Game Boy Advance', 'Game Boy Advance'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Sega Master System', 'Sega Master System'), ('Sega Genesis / Mega Drive', 'Sega Genesis / Mega Drive'), ('Sega CD', 'Sega CD'), ('32X', '32X'), ('Sega Saturn', 'Sega Saturn'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Game Gear', 'Game Gear'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation Portable (PSP)', 'PlayStation Portable (PSP)'), ('PlayStation Vita', 'PlayStation Vita'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Atari', 'Atari'), ('All Platforms', 'All Platforms')], default='All Platforms', max_length=200, verbose_name='Platform')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date'],
            },
        ),
    ]
