# Generated by Django 6.0.2 on 2026-04-15 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=255, verbose_name='Game Title')),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PlayStation 3', 'PlayStation 3'), ('Xbox', 'Xbox'), ('Switch', 'Switch'), ('SNES', 'SNES'), ('Other', 'Other')], max_length=200, verbose_name='Platform')),
                ('save_type', models.CharField(choices=[('pc', 'PC'), ('emulator', 'Emulator')], max_length=200, verbose_name='Save Type')),
                ('progress', models.CharField(choices=[('early', 'Early Game'), ('mid', 'Mid Game'), ('late', 'Late Game'), ('100', '100% Completed'), ('mission', 'Specific Mission/Custom')], max_length=200, verbose_name='Game Progress')),
                ('mission_detail', models.CharField(blank=True, help_text='Specific mission or checkpoint (optional)', max_length=200, null=True, verbose_name='Mission Detail')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('completion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Completion Percentage')),
                ('save_file', models.FileField(help_text='Max size: 50MB. Allowed formats: .zip .rar .7z .sav .srm .state .dat', upload_to='saves/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'sav', 'srm', 'state', 'dat'])], verbose_name='Save File')),
                ('save_image', models.ImageField(blank=True, help_text='Optional screenshot or cover image', null=True, upload_to='saves/images/%Y/%m/', verbose_name='Save Image')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Downloads')),
                ('upvotes', models.PositiveIntegerField(default=0, verbose_name='Upvotes')),
                ('downvotes', models.PositiveIntegerField(default=0, verbose_name='Downvotes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_saves', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Save',
                'verbose_name_plural': 'Saves',
                'ordering': ['-created_at'],
            },
        ),
    ]
