# Generated by Django 6.0.2 on 2026-04-15 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10, verbose_name='Vote Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Voted At')),
                ('save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='saves.save', verbose_name='Save')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Save Vote',
                'verbose_name_plural': 'Save Votes',
                'unique_together': {('save', 'user')},
            },
        ),
    ]
