# Generated by Django 6.0.2 on 2026-04-15 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0002_savevote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='savevote',
            old_name='save',
            new_name='save_file',
        ),
        migrations.AlterUniqueTogether(
            name='savevote',
            unique_together={('save_file', 'user')},
        ),
    ]
