# Generated by Django 6.0.2 on 2026-04-11 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Game Title')),
                ('platform', models.CharField(choices=[('NES', 'NES'), ('Famicom', 'Famicom'), ('SNES', 'SNES'), ('Super Famicom', 'Super Famicom'), ('Nintendo 64', 'Nintendo 64'), ('GameCube', 'GameCube'), ('Wii', 'Wii'), ('Wii U', 'Wii U'), ('Nintendo Switch', 'Nintendo Switch'), ('Game Boy', 'Game Boy'), ('Game Boy Color', 'Game Boy Color'), ('Game Boy Advance', 'Game Boy Advance'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Sega Master System', 'Sega Master System'), ('Sega Genesis / Mega Drive', 'Sega Genesis / Mega Drive'), ('Sega CD', 'Sega CD'), ('32X', '32X'), ('Sega Saturn', 'Sega Saturn'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Game Gear', 'Game Gear'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation Portable (PSP)', 'PlayStation Portable (PSP)'), ('PlayStation Vita', 'PlayStation Vita'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Atari', 'Atari')], max_length=50, verbose_name='Platform')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Platformer', 'Platformer'), ('RPG', 'RPG'), ('Fighting', 'Fighting'), ('Shooter', 'Shooter'), ('Puzzle', 'Puzzle'), ('Sports', 'Sports'), ('Racing', 'Racing'), ('Strategy', 'Strategy'), ('Simulation', 'Simulation'), ('Horror', 'Horror')], max_length=50, verbose_name='Genre')),
                ('description', models.TextField(verbose_name='Description')),
                ('rom_file', models.FileField(help_text='Max size: 500MB. Allowed formats: .zip .7z .rar .nes .sfc .gba .iso', upload_to='roms/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', '7z', 'rar', 'nes', 'sfc', 'gba', 'iso', 'smd', 'bin', 'cue'])], verbose_name='ROM File')),
                ('box_art', models.ImageField(help_text='Game box art image (required)', upload_to='box_art/%Y/%m/', verbose_name='Box Art')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Downloads')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_roms', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'ROM',
                'verbose_name_plural': 'ROMs',
                'ordering': ['-created_at'],
            },
        ),
    ]
