# Generated by Django 6.0.2 on 2026-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rom',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
