# Generated by Django 6.0.2 on 2026-04-11 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', verbose_name='Rating')),
                ('text', models.TextField(verbose_name='Review Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='roms.rom', verbose_name='ROM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rom_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('rom', 'user')},
            },
        ),
    ]
