# Generated by Django 6.0.2 on 2026-04-17 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Tag Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteRom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Favorited At')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rom_favorites', to='roms.rom', verbose_name='ROM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_roms', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite ROM',
                'verbose_name_plural': 'Favorite ROMs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'rom')},
            },
        ),
        migrations.AddField(
            model_name='rom',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_roms', through='roms.FavoriteRom', to=settings.AUTH_USER_MODEL, verbose_name='Favorited By'),
        ),
        migrations.AddField(
            model_name='rom',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing ROMs (e.g., "multiplayer", "classic", "arcade")', related_name='roms', to='roms.tag', verbose_name='Tags'),
        ),
    ]
