# Generated by Django 6.0.2 on 2026-04-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0005_tag_favoriterom_rom_favorited_by_rom_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Liked At')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='roms.review', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review Like',
                'verbose_name_plural': 'Review Likes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.AddField(
            model_name='review',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', through='roms.ReviewLike', to=settings.AUTH_USER_MODEL, verbose_name='Liked By'),
        ),
    ]
