PLATFORM_CHOICES = [
    ('NES', 'NES'),
    ('Famicom', 'Famicom'),
    ('SNES', 'SNES'),
    ('Super Famicom', 'Super Famicom'),
    ('Nintendo 64', 'Nintendo 64'),
    ('GameCube', 'GameCube'),
    ('Wii', 'Wii'),
    ('Wii U', 'Wii U'),
    ('Nintendo Switch', 'Nintendo Switch'),
    ('Game Boy', 'Game Boy'),
    ('Game Boy Color', 'Game Boy Color'),
    ('Game Boy Advance', 'Game Boy Advance'),
    ('Nintendo DS', 'Nintendo DS'),
    ('Nintendo 3DS', 'Nintendo 3DS'),
    ('Sega Master System', 'Sega Master System'),
    ('Sega Genesis / Mega Drive', 'Sega Genesis / Mega Drive'),
    ('Sega CD', 'Sega CD'),
    ('32X', '32X'),
    ('Sega Saturn', 'Sega Saturn'),
    ('Sega Dreamcast', 'Sega Dreamcast'),
    ('Game Gear', 'Game Gear'),
    ('PlayStation', 'PlayStation'),
    ('PlayStation 2', 'PlayStation 2'),
    ('PlayStation 3', 'PlayStation 3'),
    ('PlayStation Portable (PSP)', 'PlayStation Portable (PSP)'),
    ('PlayStation Vita', 'PlayStation Vita'),
    ('Xbox', 'Xbox'),
    ('Xbox 360', 'Xbox 360'),
    ('Xbox One', 'Xbox One'),
    ('Atari', 'Atari'),
]

GENRE_CHOICES = [
    ('Action', 'Action'),
    ('Adventure', 'Adventure'),
    ('Platformer', 'Platformer'),
    ('RPG', 'RPG'),
    ('Fighting', 'Fighting'),
    ('Shooter', 'Shooter'),
    ('Puzzle', 'Puzzle'),
    ('Sports', 'Sports'),
    ('Racing', 'Racing'),
    ('Strategy', 'Strategy'),
    ('Simulation', 'Simulation'),
    ('Horror', 'Horror'),
]
