from django.urls import path
from CheckPoint.roms import views

urlpatterns = [
    path('', views.roms, name='roms page'),
    path('top-games/', views.TopGamesView.as_view(), name='roms top games'),
    path('newly-added/', views.newly_added, name='roms newly added'),
    path('trending/', views.trending, name='roms trending'),
    path('most-downloaded/', views.most_downloaded, name='roms most downloaded'),
    # Genre pages
    path('genres/', views.genres, name='roms genres'),
    path('genres/action/', views.genre_action, name='roms genres action'),
    path('genres/adventure/', views.genre_adventure, name='roms genres adventure'),
    path('genres/platformer/', views.genre_platformer, name='roms genres platformer'),
    path('genres/rpg/', views.genre_rpg, name='roms genres rpg'),
    path('genres/fighting/', views.genre_fighting, name='roms genres fighting'),
    path('genres/shooter/', views.genre_shooter, name='roms genres shooter'),
    path('genres/puzzle/', views.genre_puzzle, name='roms genres puzzle'),
    path('genres/sports/', views.genre_sports, name='roms genres sports'),
    path('genres/racing/', views.genre_racing, name='roms genres racing'),
    path('genres/strategy/', views.genre_strategy, name='roms genres strategy'),
    path('genres/simulation/', views.genre_simulation, name='roms genres simulation'),
    path('genres/horror/', views.genre_horror, name='roms genres horror'),
    # Platforms grid
    path('platforms/', views.platforms, name='roms platforms'),
    # Platform pages
    path('platforms/nes/', views.platform_nes, name='roms platforms nes'),
    path('platforms/famicom/', views.platform_famicom, name='roms platforms famicom'),
    path('platforms/snes/', views.platform_snes, name='roms platforms snes'),
    path('platforms/super-famicom/', views.platform_super_famicom, name='roms platforms super famicom'),
    path('platforms/n64/', views.platform_n64, name='roms platforms n64'),
    path('platforms/gamecube/', views.platform_gamecube, name='roms platforms gamecube'),
    path('platforms/wii/', views.platform_wii, name='roms platforms wii'),
    path('platforms/wii-u/', views.platform_wii_u, name='roms platforms wii u'),
    path('platforms/nintendo-switch/', views.platform_nintendo_switch, name='roms platforms nintendo switch'),
    path('platforms/gameboy/', views.platform_gameboy, name='roms platforms gameboy'),
    path('platforms/gbc/', views.platform_gbc, name='roms platforms gbc'),
    path('platforms/gba/', views.platform_gba, name='roms platforms gba'),
    path('platforms/nintendo-ds/', views.platform_nintendo_ds, name='roms platforms nintendo ds'),
    path('platforms/nintendo-3ds/', views.platform_nintendo_3ds, name='roms platforms nintendo 3ds'),
    path('platforms/sega-master-system/', views.platform_sega_master_system, name='roms platforms sega master system'),
    path('platforms/genesis/', views.platform_genesis, name='roms platforms genesis'),
    path('platforms/sega-cd/', views.platform_sega_cd, name='roms platforms sega cd'),
    path('platforms/32x/', views.platform_32x, name='roms platforms 32x'),
    path('platforms/sega-saturn/', views.platform_sega_saturn, name='roms platforms sega saturn'),
    path('platforms/sega-dreamcast/', views.platform_sega_dreamcast, name='roms platforms sega dreamcast'),
    path('platforms/game-gear/', views.platform_game_gear, name='roms platforms game gear'),
    path('platforms/ps1/', views.platform_ps1, name='roms platforms ps1'),
    path('platforms/ps2/', views.platform_ps2, name='roms platforms ps2'),
    path('platforms/ps3/', views.platform_ps3, name='roms platforms ps3'),
    path('platforms/psp/', views.platform_psp, name='roms platforms psp'),
    path('platforms/vita/', views.platform_vita, name='roms platforms vita'),
    path('platforms/xbox/', views.platform_xbox, name='roms platforms xbox'),
    path('platforms/xbox-360/', views.platform_xbox_360, name='roms platforms xbox 360'),
    path('platforms/xbox-one/', views.platform_xbox_one, name='roms platforms xbox one'),
    path('platforms/atari/', views.platform_atari, name='roms platforms atari'),
    path('details/<int:pk>/', views.RomDetailView.as_view(), name='roms details'),
    path('upload/', views.RomUploadView.as_view(), name='roms upload'),
    path('delete/<int:pk>/', views.RomDeleteView.as_view(), name='roms delete'),
    path('download/<int:pk>/', views.RomDownloadView.as_view(), name='roms download'),
    path('comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment delete'),
    path('review/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review delete'),
]
