from django.urls import path
from CheckPoint.roms import views

urlpatterns = [
    path('', views.roms, name='roms page'),
    path('top-games/', views.TopGamesView.as_view(), name='roms top games'),
    path('newly-added/', views.NewlyAddedView.as_view(), name='roms newly added'),
    path('trending/', views.TrendingView.as_view(), name='roms trending'),
    path('most-downloaded/', views.MostDownloadedView.as_view(), name='roms most downloaded'),
    path('details/<int:pk>/', views.RomDetailView.as_view(), name='roms details'),
    path('upload/', views.RomUploadView.as_view(), name='roms upload'),
    path('delete/<int:pk>/', views.RomDeleteView.as_view(), name='roms delete'),
    path('download/<int:pk>/', views.RomDownloadView.as_view(), name='roms download'),
    path('comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment delete'),
    path('review/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review delete'),

    # Genre pages
    path('genres/', views.genres, name='roms genres'),
    path('genres/<str:genre>/', views.GenreDetailView.as_view(), name='roms genre detail'),
    path('genres/action/', views.GenreDetailView.as_view(), {'genre': 'action'}, name='roms genres action'),
    path('genres/adventure/', views.GenreDetailView.as_view(), {'genre': 'adventure'}, name='roms genres adventure'),
    path('genres/platformer/', views.GenreDetailView.as_view(), {'genre': 'platformer'}, name='roms genres platformer'),
    path('genres/rpg/', views.GenreDetailView.as_view(), {'genre': 'rpg'}, name='roms genres rpg'),
    path('genres/fighting/', views.GenreDetailView.as_view(), {'genre': 'fighting'}, name='roms genres fighting'),
    path('genres/shooter/', views.GenreDetailView.as_view(), {'genre': 'shooter'}, name='roms genres shooter'),
    path('genres/puzzle/', views.GenreDetailView.as_view(), {'genre': 'puzzle'}, name='roms genres puzzle'),
    path('genres/sports/', views.GenreDetailView.as_view(), {'genre': 'sports'}, name='roms genres sports'),
    path('genres/racing/', views.GenreDetailView.as_view(), {'genre': 'racing'}, name='roms genres racing'),
    path('genres/strategy/', views.GenreDetailView.as_view(), {'genre': 'strategy'}, name='roms genres strategy'),
    path('genres/simulation/', views.GenreDetailView.as_view(), {'genre': 'simulation'}, name='roms genres simulation'),
    path('genres/horror/', views.GenreDetailView.as_view(), {'genre': 'horror'}, name='roms genres horror'),

    # Platforms grid
    path('platforms/', views.platforms, name='roms platforms'),

    # Platform pages
    path('platforms/nes/', views.PlatformDetailView.as_view(), {'platform': 'nes'}, name='roms platforms nes'),
    path('platforms/famicom/', views.PlatformDetailView.as_view(), {'platform': 'famicom'}, name='roms platforms famicom'),
    path('platforms/snes/', views.PlatformDetailView.as_view(), {'platform': 'snes'}, name='roms platforms snes'),
    path('platforms/super-famicom/', views.PlatformDetailView.as_view(), {'platform': 'super-famicom'}, name='roms platforms super famicom'),
    path('platforms/n64/', views.PlatformDetailView.as_view(), {'platform': 'n64'}, name='roms platforms n64'),
    path('platforms/gamecube/', views.PlatformDetailView.as_view(), {'platform': 'gamecube'}, name='roms platforms gamecube'),
    path('platforms/wii/', views.PlatformDetailView.as_view(), {'platform': 'wii'}, name='roms platforms wii'),
    path('platforms/wii-u/', views.PlatformDetailView.as_view(), {'platform': 'wii-u'}, name='roms platforms wii u'),
    path('platforms/nintendo-switch/', views.PlatformDetailView.as_view(), {'platform': 'nintendo-switch'}, name='roms platforms nintendo switch'),
    path('platforms/gameboy/', views.PlatformDetailView.as_view(), {'platform': 'gameboy'}, name='roms platforms gameboy'),
    path('platforms/gbc/', views.PlatformDetailView.as_view(), {'platform': 'gbc'}, name='roms platforms gbc'),
    path('platforms/gba/', views.PlatformDetailView.as_view(), {'platform': 'gba'}, name='roms platforms gba'),
    path('platforms/nintendo-ds/', views.PlatformDetailView.as_view(), {'platform': 'nintendo-ds'}, name='roms platforms nintendo ds'),
    path('platforms/nintendo-3ds/', views.PlatformDetailView.as_view(), {'platform': 'nintendo-3ds'}, name='roms platforms nintendo 3ds'),
    path('platforms/sega-master-system/', views.PlatformDetailView.as_view(), {'platform': 'sega-master-system'}, name='roms platforms sega master system'),
    path('platforms/genesis/', views.PlatformDetailView.as_view(), {'platform': 'genesis'}, name='roms platforms genesis'),
    path('platforms/sega-cd/', views.PlatformDetailView.as_view(), {'platform': 'sega-cd'}, name='roms platforms sega cd'),
    path('platforms/32x/', views.PlatformDetailView.as_view(), {'platform': '32x'}, name='roms platforms 32x'),
    path('platforms/sega-saturn/', views.PlatformDetailView.as_view(), {'platform': 'sega-saturn'}, name='roms platforms sega saturn'),
    path('platforms/sega-dreamcast/', views.PlatformDetailView.as_view(), {'platform': 'sega-dreamcast'}, name='roms platforms sega dreamcast'),
    path('platforms/game-gear/', views.PlatformDetailView.as_view(), {'platform': 'game-gear'}, name='roms platforms game gear'),
    path('platforms/ps1/', views.PlatformDetailView.as_view(), {'platform': 'ps1'}, name='roms platforms ps1'),
    path('platforms/ps2/', views.PlatformDetailView.as_view(), {'platform': 'ps2'}, name='roms platforms ps2'),
    path('platforms/ps3/', views.PlatformDetailView.as_view(), {'platform': 'ps3'}, name='roms platforms ps3'),
    path('platforms/psp/', views.PlatformDetailView.as_view(), {'platform': 'psp'}, name='roms platforms psp'),
    path('platforms/vita/', views.PlatformDetailView.as_view(), {'platform': 'vita'}, name='roms platforms vita'),
    path('platforms/xbox/', views.PlatformDetailView.as_view(), {'platform': 'xbox'}, name='roms platforms xbox'),
    path('platforms/xbox-360/', views.PlatformDetailView.as_view(), {'platform': 'xbox-360'}, name='roms platforms xbox 360'),
    path('platforms/xbox-one/', views.PlatformDetailView.as_view(), {'platform': 'xbox-one'}, name='roms platforms xbox one'),
    path('platforms/atari/', views.PlatformDetailView.as_view(), {'platform': 'atari'}, name='roms platforms atari'),
]
